import Foundation

/// Executes sync operations on the filesystem (EfficientSync implementation)
///
/// **Design:**
/// - Applies operations generated by SnapshotComparator
/// - Uses ContentTracker for zero-copy deduplication
/// - Supports all operation types: add, modify, delete, move, conflict
///
/// **Conflict Resolution:**
/// - Default: newer file wins (by mtime)
/// - Future: configurable strategies (ask, keep-both)
///
/// **Example:**
/// ```swift
/// let executor = EfficientSyncExecutor()
/// let result = try executor.execute(
///     operations: ops,
///     sourceRoot: srcURL,
///     destRoot: destURL,
///     sourceSnapshot: srcSnap,
///     destSnapshot: destSnap,
///     mode: .push
/// )
/// print("Applied \(result.appliedCount) operations")
/// ```
public struct EfficientSyncExecutor {
    public init() {}

    /// Execute operations on destination
    ///
    /// - Parameters:
    ///   - operations: Operations to apply
    ///   - sourceRoot: Source directory URL
    ///   - destRoot: Destination directory URL
    ///   - sourceSnapshot: Source snapshot
    ///   - destSnapshot: Destination snapshot
    ///   - mode: Sync mode
    /// - Returns: Execution result with statistics
    public func execute(
        operations: [FileOperation],
        sourceRoot: URL,
        destRoot: URL,
        sourceSnapshot: SyncSnapshot,
        destSnapshot: SyncSnapshot,
        mode: SyncMode
    ) throws -> SyncExecutionResult {
        let tracker = ContentTracker(
            sourceSnapshot: sourceSnapshot,
            destSnapshot: destSnapshot,
            destRoot: destRoot,
            operations: operations,
            mode: mode
        )

        var result = SyncExecutionResult()

        for operation in operations {
            do {
                switch operation.action {
                case .add:
                    try applyAdd(operation, sourceRoot: sourceRoot, destRoot: destRoot, tracker: tracker)
                    result.addedCount += 1
                    result.bytesTransferred += operation.size

                case .modify:
                    try applyModify(operation, sourceRoot: sourceRoot, destRoot: destRoot, tracker: tracker)
                    result.modifiedCount += 1
                    result.bytesTransferred += operation.size

                case .delete:
                    try applyDelete(operation, destRoot: destRoot)
                    result.deletedCount += 1

                case .move(let from):
                    try applyMove(operation, from: from, destRoot: destRoot)
                    result.movedCount += 1

                case .conflict:
                    try applyConflict(operation, sourceRoot: sourceRoot, destRoot: destRoot, tracker: tracker)
                    result.conflictsResolved += 1
                    result.bytesTransferred += operation.size
                }
            } catch {
                result.errors.append(SyncExecutionError(path: operation.path, error: error))
            }
        }

        return result
    }

    // MARK: - Operation Handlers

    private func applyAdd(
        _ operation: FileOperation,
        sourceRoot: URL,
        destRoot: URL,
        tracker: ContentTracker
    ) throws {
        let destPath = destRoot.appendingPathComponent(operation.path)

        // Create parent directories
        try FileManager.default.createDirectory(
            at: destPath.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )

        // Try zero-copy from existing content
        if let existingPath = tracker.canonicalPath(for: operation.hash) {
            try FileManager.default.copyItem(at: existingPath, to: destPath)
        } else {
            // Copy from source
            let sourcePath = sourceRoot.appendingPathComponent(operation.path)
            try FileManager.default.copyItem(at: sourcePath, to: destPath)
        }

        // Update tracker
        tracker.recordWrittenContent(hash: operation.hash, at: destPath)

        // Preserve metadata
        try preserveMetadata(operation, at: destPath)
    }

    private func applyModify(
        _ operation: FileOperation,
        sourceRoot: URL,
        destRoot: URL,
        tracker: ContentTracker
    ) throws {
        let destPath = destRoot.appendingPathComponent(operation.path)

        // Remove existing file
        try? FileManager.default.removeItem(at: destPath)

        // Try zero-copy from existing content
        if let existingPath = tracker.canonicalPath(for: operation.hash) {
            try FileManager.default.copyItem(at: existingPath, to: destPath)
        } else {
            // Copy from source
            let sourcePath = sourceRoot.appendingPathComponent(operation.path)
            try FileManager.default.copyItem(at: sourcePath, to: destPath)
        }

        // Update tracker
        tracker.recordWrittenContent(hash: operation.hash, at: destPath)

        // Preserve metadata
        try preserveMetadata(operation, at: destPath)
    }

    private func applyDelete(
        _ operation: FileOperation,
        destRoot: URL
    ) throws {
        let destPath = destRoot.appendingPathComponent(operation.path)
        try FileManager.default.removeItem(at: destPath)
    }

    private func applyMove(
        _ operation: FileOperation,
        from oldPath: String,
        destRoot: URL
    ) throws {
        let sourcePath = destRoot.appendingPathComponent(oldPath)
        let destPath = destRoot.appendingPathComponent(operation.path)

        // Create parent directories for new location
        try FileManager.default.createDirectory(
            at: destPath.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )

        // Move file
        try FileManager.default.moveItem(at: sourcePath, to: destPath)
    }

    private func applyConflict(
        _ operation: FileOperation,
        sourceRoot: URL,
        destRoot: URL,
        tracker: ContentTracker
    ) throws {
        guard let localFile = operation.localFile,
              let remoteFile = operation.remoteFile else {
            throw SyncExecutorError.invalidConflictOperation(path: operation.path)
        }

        // Default resolution: newer wins
        let useRemote = remoteFile.mtime >= localFile.mtime

        if useRemote {
            // Replace with remote version
            try applyModify(operation, sourceRoot: sourceRoot, destRoot: destRoot, tracker: tracker)
        }
        // If local is newer, keep as-is (no action needed)
    }

    // MARK: - Helpers

    private func preserveMetadata(_ operation: FileOperation, at url: URL) throws {
        // Set modification time
        if operation.mtime > 0 {
            let mtime = Date(timeIntervalSince1970: TimeInterval(operation.mtime))
            try FileManager.default.setAttributes([.modificationDate: mtime], ofItemAtPath: url.path)
        }

        // Set permissions (if available)
        if let mode = operation.mode {
            try FileManager.default.setAttributes([.posixPermissions: NSNumber(value: mode)], ofItemAtPath: url.path)
        }
    }
}

// MARK: - Result Types

/// Result of sync execution
public struct SyncExecutionResult {
    public var addedCount: Int = 0
    public var modifiedCount: Int = 0
    public var deletedCount: Int = 0
    public var movedCount: Int = 0
    public var conflictsResolved: Int = 0
    public var bytesTransferred: Int64 = 0
    public var errors: [SyncExecutionError] = []

    public var totalOperations: Int {
        addedCount + modifiedCount + deletedCount + movedCount + conflictsResolved
    }

    public var hasErrors: Bool {
        !errors.isEmpty
    }
}

/// Error during sync execution
public struct SyncExecutionError: Error {
    public let path: String
    public let error: Error
}

/// Sync executor errors
public enum SyncExecutorError: Error, CustomStringConvertible {
    case invalidConflictOperation(path: String)
    case sourceFileNotFound(path: String)

    public var description: String {
        switch self {
        case .invalidConflictOperation(let path):
            return "Invalid conflict operation (missing file info): \(path)"
        case .sourceFileNotFound(let path):
            return "Source file not found: \(path)"
        }
    }
}
